#Stage 1: Running tests
FROM maven:latest AS builder

WORKDIR /app
COPY . /app

RUN mvn test

#Stage 2: Compile and run microservice if tests pass
FROM maven:latest
WORKDIR /app
COPY --from=builder /app /app

RUN mvn package
CMD ["java", "-jar", "target/accenture-techhub.war"]
