version: '3'
services:
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accwe-hospital
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  microservicio:
    build:
      context: ./
      dockerfile: Dockerfile.maven
    ports:
      - "8080:8080"
